woody-wordpress/woody-theme

library/templates/template.php, views/base.twig, views/parts/header.twig, views/parts/reveal.twig
- Règle le pb duplication des ID sur les reveal (search et lang_switcher).
- Séparation des boutons et des reveal dans des templates distincts (Compile les reveals plus qu'une fois)
- Ajouts de filtres pour permettre de customiser site par site au besoin.
=> Refactoring woody widgets with reveal

library/templates/template.php
* Différencier les blocs mobile des desktop (prq l'avoir fait sur les favoris et pas sur les autres ?) 
* Cas d'usage: cacher les blocs sur desktop pour les inserer dans une stickybar mais garder le comportement basique sur mobile (CF : le collet)
=> rename filters for mobile tools block

acf-json/group_5b2bbb46507bf.json, library/templates/template-page.php, src/js/admin/edit-post.js
https://trello.com/c/VYHZVeTF/127-le-profil-ne-doit-pas-safficher-dans-len-t%C3%AAte-si-ajouter-un-m%C3%A9dia-est-coch%C3%A9
Il y avait une condition ACF auparavant qui faisait disparaître de l'affichage le champ profil si ajouter un média est coché, et inversement.
Cette méthode créait un problème à l'enregistrement. Le champ qui disparaissait n'était pas mis à jour (Ajouter un profil ne faisait pas passer Ajouter un media a false, le champ n'était pas mis à jour). Dans la vue front les deux apparaissaient donc.
Résolution en js
=> Page teaser media OR profile bugfix

src/js/admin/woody-seo.js
L'OT saint nazaire a rencontré un problème. Dans la meta desc il y avait d'inséré une balise <span>. 
Au niveau du code, on itère dans tous les span pour ajouter le texte. Cela créait un problème de duplication de texte.Désormais on itère plus que dans .token-val ou .editable
=> push text only in editable span

library/classes/assets/class-enqueue-assets.php
Bugfix pour les pages miroirs qui référencent une page de type Playlist, la var isTouristicPlaylist était à false, et donc le style et le js n'était pas loadé
=> get referenced post page type

library/classes/process/class-woody-getters.php
Les Images des Topics ne sont pas des images enregistrées dans wordpress donc pas d'appel possible au resizer et à Cloudly
=> remove call to api cloudly for topics imgs

library/classes/content/class-unpublisher.php
Corrige la requête sql pour les planifications de dépublication.
Rajoute des quotes sur la date du jour pour éviter les erreurs.
Remplace le != '' par IS NOT NULL car != '' prend en compte forcément tous les posts et donc ne ressort rien.
=> Fix sql unpublish post

library/templates/template-page.php
Ajoute la classe "has-hero" au body si la page affiche un hero. (Utile pour savoir si on met de la transparence au menu ou non)
=> added class to body if hero exist

library/classes/process/class-woody-getters.php
=> add free ratio when icon type is img

src/js/admin/_index.js, src/js/admin/acf-wysiwyg.js
Force le retrait de tout le style lors du paste sur le wysiwyg. C'est peut-être un peu drastique mais cela évitera beaucoup de soucis à venir.
=> formating to plain text

library/classes/content/class-images.php
J'ai surchargé le test_type à l'import de fichier pour les geojson qui ne passaient plus remonté par beaucoup de monde : 
https://mantis.raccourci.fr/view.php?id=51270
https://mantis.raccourci.fr/view.php?id=51671
Quel est le soucis ? 
Dans web/wp/wp-admin/includes/file.php 
La fonction _wp_handle_upload( &$file, $overrides, $time, $action ) fait passer une batterie de tests sur les fichiers avant de les importer dans la bibliothèque. 
Dans certains cas, le "test_type" ne passe pas pour les geojson. La fonction qui va chercher l'extension du fichier ne retourne que des values false. 
L'ajout de mime_types acceptés ne suffit pas à corriger le problème. 
J'ai donc override pour ne pas passer le test quand le fichier est de type geojson via le filtre "wp_handle_upload_overrides"
Je ne trouve …
=> Override test_type for geojson files

library/classes/process/class-woody-compilers.php, library/templates/template-page.php
J'ai ajouté le tpl de hero dans les classes body sous cette forme : "has-blocks-hero-tpl_01".
Vu que cet élément est souvent le premier à être affiché sur la page, afin d'avoir des headers propres et réactifs convenables, et du fait que nous sommes souvent amenés à faire passer par dessus des éléments en fixed ou absolute, pouvoir cibler les différents tpls me semble indispensable.
Merci :)
=> add the class of hero tpl to body

library/classes/timber/class-timber-filters.php
Evite les critical errors sur le bloc socialWall en version bretonne.
(moment.php ne gère pas la locale br_BR)
=> bugfix locale

library/classes/content/class-tinymce.php
Nouveau type de liste tinymce "Suivant" (utilisant le nouveau wicon-list-style "next-icon" de la librairie)
=> [func] new tinymce list with next-icon

src/js/admin/_index.js, src/js/admin/edit-post-new-acf.js
Permet de pouvoir ouvrir et fermer les champs ACF chargés dans les nouveaux posts (sans incidence sur les posts déjà enregistrés, en brouillon ou publiés)
=> [func] close and open acf fields on new posts

acf-json/group_5d7f7cd5615c0.json, library/templates/template.php
Ajout du champ d'URL canonique dans Woody SEO, qui devient prioritaire sur le reste si elle est renseignée.
=> [func] add canonical url in woody seo

src/js/admin/woody-tpl.js
La poppin des templates apparaît désormais dans #wpbody-content car pas de #post-body-content dans le DOM dans les pages d'options ACF.
=> [edit] allow tpls choices for addon menus

acf-json/group_5b461a3831284.json
Changement de la valeur envoyée par les padding sur genericBloc, en lien avec la modification des classes concernées sur la librairie (padding et margin avec breakpoint).
Les valeurs qui étaient déjà saisies dans ce champs restent fonctionnelles, comme les deux classes ont bien été ajoutés à la librairie.
=> [fix] existing padding with breakpoint classes

src/js/admin/woody-tpl.js
Ajout des filtres de tri de templates dans les blocs "Diaporama" et "Visuel et accroche".
À valider avec la PR de la library :
https://github.com/woody-wordpress-pro/woody-library/pull/485
=> [func] add popin tpl filters for heroes & landswipers

library/templates/template-page.php
Permet d'afficher l'auteur sur les slides dans les blocs de type "Diaporama".
Correctif suite au recettage de Rochefort-en-Terre.
=> [fix] display author in landswiper

acf-json/group_5db057d2910e2.json
**Demande liée au [ticket 0058692](https://mantis.raccourci.fr/view.php?id=58692)**
Ajout d'un champs link au bloc de Logo / Image d'illustration.
_**[Pull Request liée](https://github.com/woody-wordpress-pro/woody-library/pull/585#issue-1354035198)**_
=> [FUNC] Add link to eye_candy_img

library/functions/01_assets.php
Le site key n'est plus une condition pour ajouter les icons de stations dans le backoffice.
=> [fix] add station icons in select fields when ski resort is enable

acf-json/group_5beb02e1298ce.json
Code à implémenter dans les nouvelles publicités également ?
À valider avec :
https://github.com/woody-wordpress-pro/woody-addon-claims/pull/3
https://github.com/woody-wordpress-pro/woody-library/pull/650
=> [edit] acf-json for claims

acf-json/group_5b2bbb46507bf.json, library/classes/process/class-woody-compilers.php
**Changement de l'affichage de la date**
- **Nouveau champs** "Libellé de date" dans le back office **si** le champs "Date de publication est **coché**"
- Si le champs de texte est rempli, retourne le texte saisie, sinon retourne "Publié le + date" par défaut
Sans remplir le champs : 
Après avoir rempli le champs : 
**Attention !** Cette **PR** est **liée** avec la PR sur la library (nom branch : feature/addLabelPublicationDate)
=> [0060658] add label date publi en-tête

acf-json/group_5b6c5e6ff381d.json
[Suite au ticket](https://mantis.raccourci.fr/view.php?id=63543) d'Arcachon.
si le champs n'est pas rempli, rien ne s'affiche par défaut.
Modifications : 
- Suppression de l'instruction
- Ajout d'un placeholder
Sera affiché, seulement ce qui est rentré par le client, donc si le champs est vide, rien ne s'affichera
=> [bugfix] add placeholder and rm instruction stay pages

library/classes/process/class-woody-process-tools.php
Je pense que mon correctif va régler ce type d'erreur dans NewRelic mais je veux bien un contrôle de votre part. Merci 
E_WARNING
file_get_contents(/home/admin/www/wordpress/current/web/app/themes/woody-theme/views/section_banner/section_a:2:{i:0;s:10:&quot;banner_top&quot;;i:1;s:13:&quot;banner_bottom&quot;;}.twig): failed to open stream: No such file or directory
=> Bugfix getSectionBannerFiles

acf-json/group_5b2788b48d04c.json, library/classes/process/class-woody-process.php
Ajout de la possibilité d'exclure des posts d'une mise en avant automatique (true false dans "Plus d'option")
Si le true false est activé, en champs de relation apparaît pour sélectionner les posts à exclure. Les id sont récupéré et ajouté à l'option "post__not_in" de le wp_query (class-woody-process.php)
=> [func] ajout de la possibilité d'exclure des posts d'une mise en avant automatique

acf-json/group_5bc6005838259.json
Dans les listes de contenu on ne peut mettre que des pages. 
On peut maintenant mettre des documents au format pdf comme c'est le cas pour les MEA automatique
Exemple de rendu sur les saisies
Ce bloc n'a que des templates grille, or la valeur par défaut était un slider (tpl 103), j'ai mis le tpl de grille 207 par défaut)
=> ajout de la possibilité de mettre des documents dans les listes de contenus

library/functions/01_assets.php
Fix de l'affichage des miniatures des vidéos youtube en front
Avant:
Après:
=> [FEAT] Fix youtube thumb

acf-json/group_5bc6079fe9b0a.json, library/classes/process/class-woody-compilers.php, library/classes/process/class-woody-getters.php, library/classes/process/class-woody-process.php
Ajout d'un filtre de recherche par mots clés dans le bloc de liste de contenu. La recherche s'effectue uniquement dans le titre des posts (pages et documents)
/!\ : lié avec la [PR suivante](https://git.rc-prod.com/raccourci/woody-wordpress/addons/woody-library/-/merge_requests/769) sur la librairie
=> Add filter content list

library/classes/process/class-woody-getters.php
Sur les MEA, certaines images de fiches SIT sont étirées
On applique un remplacement pour changer le crop de l'image dans l'url
=> [fix] str_replace sur le crop des img venant api.cloudly.space

acf-json/group_5b2bbb46507bf.json
[Ticket des 2 alpes](https://mantis.raccourci.fr/view.php?id=67138)
Ajout d'un field "contributor" dans le page teaser
⚠️ : En lien avec la [MR sur la library](https://git.rc-prod.com/raccourci/woody-wordpress/addons/woody-library/-/merge_requests/810)
=> add contributor field in page teaser

library/classes/process/class-woody-getters.php
Ticket 68387 de Saint gervais
La méthode de crop étirait l'image si le MEA était en portrait ce qui la rendait floue
- Avec la méthode "clip" :
- Avec la méthode "crop" :
=> [TCK0068387|FIX] fix crop ratio on SIT MEA

views/base.twig
Ticket de [Cote Landes Nature](https://mantis.raccourci.fr/view.php?id=66939)
L'icone du site ne s'affiche pas dans les favoris IOS sur Safari (fonctionne sur Chrome)
Ajout de crop supplémentaires pour gérer cet affichage
=> [TCK66939] ajout de taille d'icone pour les favoris Safari IOS

acf-json/group_5b043614df4a6.json
Actuellement, on peut aligner les boutons à gauche, au milieu ou à droite. En mobile, on garde cette alignement. Pour des questions d'accessibilité, il est conseillé de centrer les boutons. Pour permettre cet alignement sans "limité" la fonctionnalité, on peut géré l'alignement mobile via le back office. Si on ne coche pas "Modifier l'alignement mobile", on garde le comportement desktop.
MODIFICATIONS : 
- update du composant JSON pour ajouter le true_false et le sélecteur
PR lié avec la [MR](https://git.rc-prod.com/raccourci/woody-wordpress/addons/woody-library/-/merge_requests/824) sur la library :
=> [feature] add ACF fields for button component

library/classes/process/class-woody-process-tools.php
- [Blois chambord - section 2](https://m.bloischambord.com/decouvrir-la-destination/nos-chateaux-de-la-loire/le-chateau-de-blois/)
=> [fix] include array of all selected terms in wp query

src/scss/admin/acf.scss
Masquage du "Bloc de réservation" dans le BO
Depuis l'ajout du bloc "Formulaire de réservation" disponible dans les sections, le bloc de résa est obsolète. De plus, il nécessite une surcharge de style pour qu'il soit visible et n'est pas adapté à tous les templates de landswpr.
Le masquage en SCSS évitera qu'il soit de nouveau utiliser sans impacter les sites utilisant cette fonctionnalité
=> display none bookblock in BO

views/base.twig
Traduction des aria-label des flèches de swiper en JS.
Traductions faites en Français, Allemand, Italien, Néerlandais, Anglais (default)
Ordonnancement du DOM
Le header remonte au dessus du DOM
Suppression de la classe `flex-dir-column-reverse`
Les sites actuels ont leur header en `fixed`, niveau front, ça ne change rien sur ces sites. Pour les autres, la suppression de la classe `flex-dir-column-reverse` permet de laisser le header au dessus du contenu du site
=> [ACCESS] re-order DOM

src/scss/admin/acf.scss
Ajouter un flex-wrap sur les options de couleurs pour les boutons et les bordures afin d'éviter un débordement dans le back-office
=> [style] reponsive options colors back-office

library/classes/process/class-woody-compilers.php
Le bouton de profil ne s'affichait que sur les profils manuels
=> [FIX] Page teaser profil button

library/functions/01_assets.php
See [Woody Addon Hawwwai PR](https://git.rc-prod.com/raccourci/woody-wordpress/addons/woody-addon-hawwwai/-/merge_requests/98)
=> [edit] escape str to time formatDate function

acf-json/group_5b0d1ed32a384.json, acf-json/group_5b2788b48d04c.json, library/classes/process/class-woody-getters.php
Pour le développement de Dunkerque, il y a un coeur de favoris directement sur les card de mise en avant, comme c'est le cas sur les MEA YouBook
On peut donc désormais, dans le backoffice les blocs de MEA (manuel, auto SIT et auto Page) cocher la case "Favoris" pour faire apparaître le coeur de favoris sur les cards.
:warning: Cette MR est liée à celle sur [l'addon Hawwwai](https://git.rc-prod.com/raccourci/woody-wordpress/addons/woody-addon-hawwwai/-/merge_requests/104) et celle sur la [library](https://git.rc-prod.com/raccourci/woody-wordpress/addons/woody-library/-/merge_requests/928)
=> [feat] add fav icon on MEA

library/classes/process/class-woody-compilers.php
En raison du RGAA, on doit ajouter un attribut `aria-label="Page X"` à la pagination des listes de contenu.
On utilise une fonction native de Wordpress pour générer la pagination (`paginate_links`). En utilisant le hook `paginate_links_output` on peut récupérer la compilation HTML sous forme de string et faire des changements.
A partir d'une regex, on peut récupérer les liens et ajouter le aria-label et le remplir avec le contenu du lien.
J'ai également fait la modification pour récupérer le "Page précédente" et "Page suivante"
On obtient le HTML suivant
```html
<ul class='page-numbers'>
<li><a class="prev page-numbers"  href="http://www.dunkerque.wp.rc-dev.com/rgaa/" aria-label="Page précédente">« Précédent</a></li>
<li><a class="page-numbers" …
```
=> [FEATURE|RGAA] add aria label on content list pagination
