library/functions/03_woody_format_data.php
Fix: Affichage des routes même si il n'y a pas de marqueurs. 
Temporaire: Marqueurs présent dans les fichiers de route/zone sont cachés ( décalage ). Le traitement pour les ajouter sur la carte est en commentaire.
=> format geomap data (route case)

library/functions/03_woody_format_data.php
Remplacement des virgules par des points dans les coordonnées gps le cas échéant
=> replace every , by . in coordinates

library/classes/content/class-shortcodes.php, src/js/front/plugins/search.js
Prise en charge des arguments "tags" lors de la recherche ES en ajax
=> Allow searching by tags with ajax

acf-json/group_5b6c5e6ff381d.json
Ajout d'un champ de type nombre pour avoir un prix pour les dimanches et jours fériés.
=> add sunday & holidays price option

library/functions/04_custom_appearance.php
=> add query parameters when sharing url

acf-json/group_5c4f2efaccd2f.json, library/classes/process/class-woody-compilers.php
Ajouter un champ pour ordonner les résultats des cocons sémantiques (Aléatoire OU dans l'ordre des pages uniquement)
=> semantic view order rand/page order

library/templates/template.php
https://trello.com/c/KNPvNtuq/258-ajouter-la-balise-noindex-no-follows-sur-tous-les-mod%C3%A8les
metas noindex nofollow pour les modèles
=> no index no follow for woody model

library/classes/process/class-woody-getters.php
Afficher tous les "Bons Plans" d'une fiche SIT dans la mise en avant
=> display all deals

library/classes/process/class-woody-getters.php
Ticket Bagnole de l'orne. Date des mises en avant de FMA.
On ne prend plus juste la première. On choisit la prochaine dont la date de fin n'est pas passée.
=> take first date not passed yet

library/classes/content/class-taxonomy.php, library/classes/process/class-woody-getters.php
https://docs.google.com/document/d/1WgRX-zQ50RYSVGGTA81Of-7endiD-V5zNUfLhPL_Ka0/edit#heading=h.pqm034x9lu5g
Changements souhaités pour le 20 Avril
=> location for topics

library/classes/content/class-unpublisher.php
remove unpublished date when "time() > _wUnpublisher_date" and post -> draft
=> remove the Unpublished date

library/classes/content/class-permalink.php
Les liens comme https://www.tourismebretagne.com/destinations/les-10-destinations/cote-de-granit-rose-baie-de-morlaix/912/
fonctionnent alors qu'il ne devrait pas (la page 912 est inexistante).
Dans cet exemple "912" est interprété comme une pagination.
Je redirige ces pages
=> redirect if wrong pagination

acf-json/group_5d7f7cd5615c0.json
Ajout d'un bouton "Exclure de la recherche"
=> add remove es index field

library/classes/process/class-woody-process.php
A passer en même temps que la même pull request de la library.
=> load img_mobile_url on interractive gallery

views/parts/header.twig
=> Add class to header tools list : tools.list_class

acf-json/group_5bc6079fe9b0a.json, library/classes/process/class-woody-getters.php
ajout de l'option "auto_open" dans les paramètres de mise en page des filtres.
A passer en même temps que la pull-request du même nom dans la library.
=> add new option auto_open

library/classes/process/class-woody-compilers.php
Ajout de la liste des classes dans la variable pour les heros
=> Added the var for classlist in compilers

library/classes/acf/class-acf.php
=> new Tpl Focus 324

library/classes/process/class-woody-compilers.php, library/classes/process/class-woody-process.php
Récupère le titre du sommaire et l'ajoute sur une ancre.
=> sommaire section

acf-json/group_5b2788b48d04c.json, library/classes/process/class-woody-compilers.php, library/classes/process/class-woody-getters.php
J'ai ajouté le champ case à cocher pour afficher la date de publication et fais le traitement à envoyer au twig.
=> add created post date

views/macros/macros.twig
J'ai changé la manière dont se comportent les macros.
Chaque macro doit être indépendante (dommage...).
=> change behavior of macros in twig

library/classes/acf/class-acf.php, src/js/admin/ajax-load-layouts.js
@benbchd Tu as la liste des tests que j'ai effectué sur la tache clickup (sous tache correctif bug)
=> Load blocks clone later

library/templates/template-page.php
Le pb doit venir du fait que l'instance de GroupQuotation se fait dans un statement if, et que dans un autre if plus bas on réutilise cette instance sans s'assurer qu'elle a bien été créée. J'ai remonté l'instance plus haut pour éviter ce soucis
=> fix instance

library/classes/process/class-woody-compilers.php, library/classes/process/class-woody-getters.php
Modification du traitement des données title de mini fiche sit, suppression des "TODO" qui s'affichent en front pour le prix..
=> fix minisheet price (removed for now) and add titles display

library/classes/process/class-woody-compilers.php, library/classes/process/class-woody-getters.php
J'ai été obligé d'ajouter cette condition, car le fait de mettre ellipsis à false, ça fait que les |default dans le twig viennent lui écrire 180 (et c'est pas ce qu'on veut..)
=> let the text with wysiwyg when focus custom content

acf-json/group_5b042f5ad9ecc.json, acf-json/group_5b461a3831284.json, library/classes/timber/class-timber-filters.php
- Ajout des options ACF sur les blocs Texte libre et CTA pour sélectionner la position verticale du bloc
- Ajout de la fonction twig "spacing" qui permet de filtrer les espaces blancs au delà de 1 (utile pour l'ajout de classes).
=> Add Json and twig func

acf-json/group_5b2788b48d04c.json, library/classes/process/class-woody-getters.php
le switch sur woody_topic est-il nécessaire ?
=> [func] add pinnable content option

acf-json/group_5b91291196e19.json
Ajout de FAQ dans les groupes d'onglets. (demande de Manon)
=> add faq to groups

acf-json/group_5b4726f891221.json
Modification liée à une modification sur la library
=> [func] add vertical alignment in tabs

src/js/admin/edit-post-new-acf.js
Possibilité de cliquer sur toute la barre du groupe de champ acf sur un nouveau post
=> [fix] up click to toggle acf field on new post

acf-json/group_5afd260eeb4ab.json, acf-json/group_615dbea3b8aa7.json, library/classes/content/class-sitemap.php
- Ajout du group ACF
- Clonage du groupe ACF dans section
- Ajout du add_filter dans class-sitemap.php
=> [func] convert shortcode to blocs - Sitemap

library/classes/process/class-woody-compilers.php, library/classes/process/class-woody-getters.php
Permet d'afficher les boutons des cards en lists grids.
=> [fix] Add card buttons to list grids

acf-json/group_5bb325e8b6b43.json, library/templates/template-page.php
Ajout du bouton "Voir la vidéo" dans les Landswpr.
@benbchd : A passer en même temps que la branche "Mediajs" de la library.
=> add Presentation video For Landswpr

views/parts/header.twig
Utile pour faire un préloader custom au chargement de la page (pour Cannes uniquement sur la home)
=> [func] add preloader in page parts

acf-json/group_5d7f7cd5615c0.json, library/classes/content/class-sitemap.php
Ajoute un bouton permettant de désactiver l'indexation de la page dans le sitemap.
=> [func] Add Sitemap checkbox for pages yes/no

library/classes/content/class-sitemap.php
Ajout du xKey pour le shortcode sitemap.
=> Add xKey sitemap to shortcode sitemap

acf-json/group_5ed7a3b9c0e0e.json
À valider avec :
https://github.com/woody-wordpress-pro/woody-library/pull/463
=> [edit] update acf-json with display anchor index option

acf-json/group_5afd260eeb4ab.json, acf-json/group_61f24dc3c8810.json, library/classes/process/class-woody-process.php, src/scss/admin/acf.scss
À valider avec :
https://github.com/woody-wordpress-pro/woody-library/pull/464
=> [func] add spacing block

library/templates/template-page.php, views/page404.twig
Filtre pour Belle-Ile souhaitant une page 404 personnalisée.
=> [func] add filter for custom html in 404 page

acf-json/group_5afd260eeb4ab.json
=> [edit] wording acf-json section

library/classes/acf/class-acf.php, library/functions/01_assets.php, src/scss/admin/woody-tpls.scss
À valider avec :
https://github.com/woody-wordpress-pro/woody-library/pull/496
=> [func] add badge for new woody tpls in back office

library/classes/menus/class-woody-menus.php
On récupère le titre du lien externe, s'il est vide, on check si le lien externe correspond à un des posts du site, si oui, on prend le titre du post
=> [FIX] Use external link title

acf-json/group_5e16e3b48d2d6.json, library/templates/template.php, views/parts/schemaGraph.twig
- Ajout d'un champ **"Ville"**
- Corrections de noms de champs affichés (**addressCountry** et **addressLocality**)
- Ajout d'un filtre **"woody_tourist_more_informations"** pour ajouter des informations spécifiques à chaque site
=> [edit] tourist informations country and more infos filter

library/templates/template-page.php
Utile pour Cannes pour surcharger le crop d'image en mobile :)
=> [func] add filter for setting lazy img in landswpr slide

library/classes/process/class-woody-compilers.php
- Ajout des textes du bookblock en variables
- Parmi les textes, option pour l'affichage d'une option de base dans le select des playlists
_En lien avec la PR "Bookblock Texts" sur woody-library_
=> Bookblock Texts

library/functions/03_helpers.php
À merger avec :
https://github.com/woody-wordpress-pro/woody-addon-menus/pull/11
=> [func] add getFieldAndFallback func in helpers

acf-json/group_5b052bbee40a4.json
Fields to add complementary images in heroes
=> [func] More hero's imgs

library/classes/content/class-robots.php
PR suite au ticket des 2 Alpes
=> [func] add new rule in robots.txt

acf-json/group_5ea2f8fe7fa8f.json, library/classes/process/class-woody-getters.php
Possibilité de lier un profil existant à une page pour l'afficher dans une MEA (en + d'un profil personnalisé).
=> [func] allow linked existing profile

library/classes/process/class-woody-compilers.php
Cf ticket hero Marseille : https://mantis.raccourci.fr/view.php?id=59881
À valider avec le [PR de la library](https://github.com/woody-wordpress-pro/woody-library/pull/640).
=> [func] add new variable in formatPageHero function

acf-json/group_6386101c8e5f6.json, library/classes/roles/class-users-restrictions.php
Tâche clickup :
https://app.clickup.com/t/860pbfzm1
Explication :
J'ai un hook qui vient faire une action lors de chargement du champ 'users'.
Ce hook appelle une méthode qui permet d'ajouter les roles aux champ en enlevant 'administrateur'.
=> Feature to add filter to user restriction admin

library/classes/process/class-woody-compilers.php
À valider avec la PR suivante :
https://github.com/woody-wordpress-pro/woody-addon-hawwwai/pull/24
=> [func] add filter in createBreadcrumb func for hawwwai

acf-json/group_5ed0c08a3ee10.json
Utile pour le module "Organigramme"
=> [func] add profile_type field in profile CPT

acf-json/group_5b052bbee40a4.json
Ajout de l'affichage du visuel et accroche sur les pages de circuits
=> [BUGFIX] Ajout du visuel et accroche pour les pages de type Circuit

library/templates/template.php
https://app.clickup.com/4572633/v/dc/4bhet-11868/4bhet-9185
=> [FUNC] Ajout d'un apply_filter pour ajouter des langues

acf-json/group_5b052bbee40a4.json
=> [BUGFIX] Ajout des visuels et accroches sur les pages de type 'circuit'

acf-json/group_5b471f2922b04.json
À valider avec la [PR de woody-library](https://github.com/woody-wordpress-pro/woody-library/pull/698)
=> [func] add block titles to tabs layout in acf-json

acf-json/group_5b4726f891221.json, library/classes/process/class-woody-process.php
=> [func] allow no padding on tabs options

src/js/front/framework/foundation-explicit-pieces.js
Ajout de l'import du drilldown pour le tpl 02 du menu mobile
=> add import for mobile menu drilldown

library/classes/process/class-woody-process-tools.php
ajout du context 'display_fullwidth' in getDisplayOptions
=> [edit] add new context 'display_fullwidth' in getDisplayOptions

library/classes/content/class-api-rest.php
Ajout d'élément dans le retour api du get page preview
=> add element in api rest

library/functions/01_assets.php, src/scss/admin/acf.scss
Modification de la fonction de formatage des dates : 
- Ajout d'un paramètre locale pour traduire la date retournée
Ajout de l'icône sur le nouveau bloc snowflake
=> [feature] update formatDAte() && icone météo snowflake

library/classes/process/class-woody-process.php
=> [func] use moment format function for video update url structured data

src/scss/admin/acf.scss
Ajout de l'icône pour le bloc Infos Route de l'addon snowflake
=> [style] add icon for info route bloc

acf-json/group_5b043614df4a6.json, library/classes/process/class-woody-process.php
=> [func] add btn click event GA

library/classes/process/class-woody-process.php
Ajout d'un filtre permettant d'ajouter un contenu additionnel dans le socialwall. 
En ce branchant dessus, on peut envoyer un bout de DOM qui sera afficher sous la description.
=> [feature] add filter to add content in socialwall

src/scss/admin/acf.scss
Ajout d'un icone en Backoffice pour le bloc "Messages Lumiplan"
=> [style] add icon for lumiplay messages bloc

library/classes/acf/class-acf.php
Le hook était fait sur le section content ce qui oblige à faire des boucles, aller chercher le field à la main etc...
Changement du hook pour se brancher directement sur le load field du champs menu_type
=> improvement menu bloc

library/classes/process/class-woody-getters.php
=> [fix] test if primary term

library/classes/process/class-woody-getters.php
[Woody library: merge request ](https://git.rc-prod.com/raccourci/woody-wordpress/addons/woody-library/-/merge_requests/862)
=> [func] add wrapper mobile behavious in subcontent

library/classes/process/class-woody-getters.php
=> [fix] sheet rating getter && add HLO bordereau

acf-json/group_5b2788b48d04c.json, acf-json/group_5bb325e8b6b43.json, acf-json/group_669698072603c.json, library/classes/process/class-woody-compilers.php, library/classes/process/class-woody-process.php
- [URL DU TICKET](https://mantis.raccourci.fr/view.php?id=71447)
=> [func] order by title ASC filter

library/classes/roles/Roles.php
Ajout d'un filtre permettant de modifier les données dans le formulaire des pages protégées par un mot de passe.
=> [func] add filter on protected form data

acf-json/group_5bc6079fe9b0a.json, library/classes/process/class-woody-compilers.php, library/classes/process/class-woody-getters.php, library/classes/process/class-woody-process.php
PR liée : https://git.rc-prod.com/raccourci/woody-wordpress/addons/woody-library/-/merge_requests/new?merge_request%5Bsource_branch%5D=feat%2FblocListAddProfil
=> [FEAT] Ajout du tri par profil lié
